title: 菩提道次第广论学习资源
description: 广论文档与视频学习资源
baseurl: ""
url: ""
github_username: adm2936

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"